export const ModelSocketId = {
  HEAD: "HEAD",
  SPINE: "SPINE",
  LEFT_SHOULDER: "LEFT_SHOULDER",
  LEFT_ELBOW: "LEFT_ELBOW",
  LEFT_HAND: "LEFT_HAND",
  RIGHT_SHOULDER: "RIGHT_SHOULDER",
  RIGHT_ELBOW: "RIGHT_ELBOW",
  RIGHT_HAND: "RIGHT_HAND",
};
