export const ModelSocketId = {
  SPINE: "SPINE",
  LEFT_HAND: "LEFT_HAND",
  RIGHT_HAND: "RIGHT_HAND",
  PROJECTILE_START: "PROJECTILE_START",
};

export const UnitAnimationId = {
  IDLE: "IDLE",
  AIMING_IDLE: "AIMING_IDLE",
  JUMP_LOOP: "JUMP_LOOP",
  WALK: "WALK",
  RUN: "RUN",
  AIMING_WALK: "AIMING_WALK",
  AIMING_RUN: "AIMING_RUN",
  WALK_BACKWARDS: "WALK_BACKWARDS",
  STRAFE_RIGHT: "STRAFE_RIGHT",
  STRAFE_LEFT: "STRAFE_LEFT",
};
