export const WorldModuleId = {
  OCTREE: "OCTREE",
  PROJECTILES: "PROJECTILES",
  COLLECTIBLE: "COLLECTIBLE",
  REGION: "REGION",
};

export const UnitModuleId = {
  AIMING: "AIMING",
  UNIT_CONTROLLER: "UNIT_CONTROLLER",
  ABILITIES: "ABILITIES",
};
