export const WorldModuleId = {
  OCTREE: "OCTREE",
  PROJECTILES: "PROJECTILES",
  COLLECTIBLES: "COLLECTIBLES",
  REGION: "REGION",
  VERLET_INTEGRATION: "VERLET_INTEGRATION",
  OCTREE_CAR: "OCTREE_CAR",
  UNITS: "UNITS",
  PLAYER_CONTROLLER: "PLAYER_CONTROLLER",
  THIRD_PERSON_CAMERA: "THIRD_PERSON_CAMERA",
};

export const UnitModuleId = {
  AIMING: "AIMING",
  ABILITIES: "ABILITIES",
  TPS_MOVEMENT: "TPS_MOVEMENT",
};
